approval_policy = "never"
disable_response_storage = false
experimental_use_rmcp_client = true
file_opener = "cursor"
hide_agent_reasoning = false
model = "gpt-5"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
model_supports_reasoning_summaries = true
model_verbosity = "medium"
preferred_auth_method = "chatgpt"
sandbox_mode = "danger-full-access"
show_raw_agent_reasoning = false

[profiles.plan]
model = "gpt-5"
model_reasoning_effort = "high"
model_verbosity = "high"

[profiles.act]
model = "gpt-5"
model_reasoning_effort = "medium"
model_verbosity = "low"

[history]
persistence = "save-all"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.sentry]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://mcp.sentry.dev/mcp"]

[sandbox_workspace_write]
network_access = true

[tools]
web_search = true
