approval_policy = "never"
disable_response_storage = false
file_opener = "cursor"
hide_agent_reasoning = false
model = "gpt-5"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
model_supports_reasoning_summaries = true
model_verbosity = "medium"
preferred_auth_method = "chatgpt"
sandbox_mode = "workspace-write"
show_raw_agent_reasoning = false

[features]
rmcp_client = true
web_search_request = true

[history]
persistence = "save-all"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.sentry]
command = "npx"
args = ["-y", "mcp-remote@latest", "https://mcp.sentry.dev/mcp"]

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
inherit = "all"
exclude = [
    "AWS_*",
    "SENTRY_*",
    "*_CC_*",
    "*_CLIENT_ID",
    "*_KEY",
    "*_PASSWORD",
    "*_SECRET",
    "*_TOKEN",
    "*_USERNAME",
]

[tools]
web_search = true
view_image = true

[tui]
notifications = true
